version: '3.7'
services: 
    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306        
        environment:
          MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ../mysql-db:/var/lib/mysql  
    api:
        container_name: api
        image: capacitacion/api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 11000:3000
        environment:
            MYSQL_CONNECTION_STRING: mysql://root:admin@mysqldb/capacitacion?debug=true&charset=UTF8_GENERAL_CI&timezone=-0700
        volumes:
            - .:/usr/src/app
networks:
    default: