version: '3.7'
services: 
    api:
        container_name: api
        image: capacitacion/api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 11000:3000
        volumes:
            - .:/usr/src/app
networks:
    default: